@startuml
!include .\Application\BubbleSortExecutable.puml
!include .\Application\SortObserver.puml
!include .\Application\TextControl.puml
!include .\Framework\IObserver.puml
!include .\Framework\Observable.puml
!include .\Framework\SortExecutable.puml
!include .\Properties\AssemblyInfo.puml
!include .\obj\Debug\.NETFramework,Version=v4.7.2.AssemblyAttributes.puml
@enduml
